/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ConfirmMessageBox: typeof import('./components/custom/elements/ConfirmMessageBox.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    GameCard: typeof import('./components/custom/GameCard.vue')['default']
    GameResult: typeof import('./components/tictactoe/GameResult.vue')['default']
    HeaderNav: typeof import('./components/layouts/HeaderNav.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HouseCardWidget: typeof import('./components/widgets/HouseCardWidget.vue')['default']
    KathBadge: typeof import('./components/custom/elements/KathBadge.vue')['default']
    KathDialog: typeof import('./components/custom/elements/KathDialog.vue')['default']
    LoadingPage: typeof import('./components/LoadingPage.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    MainButton: typeof import('./components/custom/MainButton.vue')['default']
    MainFooter: typeof import('./components/layouts/MainFooter.vue')['default']
    MainHeader: typeof import('./components/layouts/MainHeader.vue')['default']
    MainTable: typeof import('./components/custom/MainTable.vue')['default']
    MainTableActions: typeof import('./components/custom/MainTableActions.vue')['default']
    PageCard: typeof import('./components/custom/PageCard.vue')['default']
    PasswordField: typeof import('./components/inputs/PasswordField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsCard: typeof import('./components/custom/SettingsCard.vue')['default']
    ShapeForm: typeof import('./components/settings/ShapeForm.vue')['default']
    ShapeList: typeof import('./components/settings/ShapeList.vue')['default']
    SideNav: typeof import('./components/layouts/SideNav.vue')['default']
    SquareBoxes: typeof import('./components/tictactoe/SquareBoxes.vue')['default']
  }
}
