/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    GameResult: typeof import('./components/tictactoe/GameResult.vue')['default']
    HeaderNav: typeof import('./components/layouts/HeaderNav.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HouseCardWidget: typeof import('./components/widgets/HouseCardWidget.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    MainFooter: typeof import('./components/layouts/MainFooter.vue')['default']
    MainHeader: typeof import('./components/layouts/MainHeader.vue')['default']
    PasswordField: typeof import('./components/inputs/PasswordField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./components/layouts/SideNav.vue')['default']
    SquareBoxes: typeof import('./components/tictactoe/SquareBoxes.vue')['default']
  }
}
